spring.config.activate.on-profile=sit

spring.datasource.url=${SIT_DB_URL:${DB_URL:}}
spring.datasource.username=${SIT_DB_USERNAME:${DB_USERNAME:}}
spring.datasource.password=${SIT_DB_PASSWORD:${DB_PASSWORD:}}

spring.flyway.url=${SIT_DB_URL:${DB_URL:}}
spring.flyway.user=${SIT_DB_USERNAME:${DB_USERNAME:}}
spring.flyway.password=${SIT_DB_PASSWORD:${DB_PASSWORD:}}

app.jwt.secret=${SIT_JWT_SECRET:${JWT_SECRET:change-this-to-a-long-random-secret-key-for-prod}}
