INSERT INTO ERM_USERS (
    USERNAME,
    EMAIL,
    FULL_NAME,
    DEPARTMENT,
    EMPLOYMENT_STATUS,
    PASSWORD_HASH,
    IS_ACTIVE,
    REPORTING_MANAGER_USER_ID,
    REPORTING_MANAGER_ROLE_NAME
)
SELECT
    LOWER(r.GENERATED_EMPLOYEE_ID) AS USERNAME,
    LOWER(r.GENERATED_EMAIL_ADDRESS) AS EMAIL,
    CONCAT(r.FIRST_NAME, ' ', r.LAST_NAME) AS FULL_NAME,
    COALESCE(m.DEPARTMENT, 'General') AS DEPARTMENT,
    'Active' AS EMPLOYMENT_STATUS,
    '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq' AS PASSWORD_HASH,
    1 AS IS_ACTIVE,
    r.REPORTING_MANAGER_USER_ID,
    r.REPORTING_MANAGER_ROLE_NAME
FROM ERM_ONBOARDING_REQUESTS r
LEFT JOIN ERM_USERS m ON m.ID = r.REPORTING_MANAGER_USER_ID
WHERE r.WORKFLOW_STAGE = 'SUPER_ADMIN_APPROVED'
  AND r.GENERATED_EMPLOYEE_ID IS NOT NULL
  AND r.GENERATED_EMAIL_ADDRESS IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM ERM_USERS u
      WHERE LOWER(u.USERNAME) = LOWER(r.GENERATED_EMPLOYEE_ID)
         OR LOWER(u.EMAIL) = LOWER(r.GENERATED_EMAIL_ADDRESS)
  );

INSERT INTO ERM_USER_ROLES (USER_ID, ROLE_ID)
SELECT u.ID, r.ID
FROM ERM_USERS u
JOIN ERM_ONBOARDING_REQUESTS o
  ON LOWER(u.USERNAME) = LOWER(o.GENERATED_EMPLOYEE_ID)
JOIN ERM_ROLES r
  ON LOWER(r.ROLE_NAME) = LOWER(o.DESIGNATION_ROLE_NAME)
WHERE o.WORKFLOW_STAGE = 'SUPER_ADMIN_APPROVED'
  AND o.GENERATED_EMPLOYEE_ID IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM ERM_USER_ROLES ur
      WHERE ur.USER_ID = u.ID
        AND ur.ROLE_ID = r.ID
  );
