CREATE TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS
(
    ID                                   BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_USER_ID                     BIGINT       NOT NULL,
    EMPLOYEE_USERNAME                    VARCHAR(100) NOT NULL,
    EMPLOYEE_FULL_NAME                   VARCHAR(150) NOT NULL,
    CURRENT_DESIGNATION_ROLE_NAME        VARCHAR(100) NOT NULL,
    REQUESTED_DESIGNATION_ROLE_NAME      VARCHAR(100) NOT NULL,
    REQUESTED_REPORTING_MANAGER_USER_ID  BIGINT       NOT NULL,
    REQUESTED_REPORTING_MANAGER_USERNAME VARCHAR(100) NOT NULL,
    REQUESTED_REPORTING_MANAGER_FULL_NAME VARCHAR(150) NOT NULL,
    REQUESTED_REPORTING_MANAGER_ROLE_NAME VARCHAR(100) NOT NULL,
    WORKFLOW_STAGE                       VARCHAR(40)  NOT NULL DEFAULT 'HR_SUBMITTED',
    CREATED_BY_USERNAME                  VARCHAR(100) NOT NULL,
    HR_COMMENT                           VARCHAR(500) NULL,
    HEAD_HR_COMMENT                      VARCHAR(500) NULL,
    CHRO_COMMENT                         VARCHAR(500) NULL,
    SUPER_ADMIN_COMMENT                  VARCHAR(500) NULL,
    HR_ACTION_BY                         VARCHAR(100) NULL,
    HEAD_HR_ACTION_BY                    VARCHAR(100) NULL,
    CHRO_ACTION_BY                       VARCHAR(100) NULL,
    SUPER_ADMIN_ACTION_BY                VARCHAR(100) NULL,
    HR_ACTION_AT                         TIMESTAMP    NULL,
    HEAD_HR_ACTION_AT                    TIMESTAMP    NULL,
    CHRO_ACTION_AT                       TIMESTAMP    NULL,
    SUPER_ADMIN_ACTION_AT                TIMESTAMP    NULL,
    CREATED_AT                           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ERM_EMP_DATA_REQ_EMPLOYEE_USER_ID ON ERM_EMPLOYEE_DESIGNATION_REQUESTS (EMPLOYEE_USER_ID);
CREATE INDEX IDX_ERM_EMP_DATA_REQ_WORKFLOW_STAGE ON ERM_EMPLOYEE_DESIGNATION_REQUESTS (WORKFLOW_STAGE);

INSERT INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER, IS_ACTIVE)
SELECT 'employee-data', 'Employee Data', '/employee-data', 'contact-round', 3, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_NAV_MENUS WHERE MENU_CODE = 'employee-data');

UPDATE ERM_NAV_MENUS
SET SORT_ORDER = SORT_ORDER + 1
WHERE MENU_CODE IN ('onboarding', 'projects', 'attendance', 'leaves', 'settings');

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'employee-data'
WHERE r.ROLE_NAME IN ('Super Admin', 'CHRO', 'HR Head', 'Senior HR');
