CREATE TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
(
    ID                        BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_USER_ID          BIGINT       NOT NULL,
    EMPLOYEE_USERNAME         VARCHAR(100) NOT NULL,
    CURRENT_FULL_NAME         VARCHAR(150) NOT NULL,
    CURRENT_EMAIL             VARCHAR(150) NOT NULL,
    CURRENT_DEPARTMENT        VARCHAR(100) NOT NULL,
    CURRENT_EMPLOYMENT_STATUS VARCHAR(30)  NOT NULL,
    REQUESTED_FULL_NAME       VARCHAR(150) NOT NULL,
    REQUESTED_EMAIL           VARCHAR(150) NOT NULL,
    REQUESTED_DEPARTMENT      VARCHAR(100) NOT NULL,
    REQUESTED_EMPLOYMENT_STATUS VARCHAR(30) NOT NULL,
    WORKFLOW_STAGE            VARCHAR(40)  NOT NULL DEFAULT 'HR_SUBMITTED',
    CREATED_BY_USERNAME       VARCHAR(100) NOT NULL,
    HR_COMMENT                VARCHAR(500) NULL,
    HEAD_HR_COMMENT           VARCHAR(500) NULL,
    CHRO_COMMENT              VARCHAR(500) NULL,
    SUPER_ADMIN_COMMENT       VARCHAR(500) NULL,
    HR_ACTION_BY              VARCHAR(100) NULL,
    HEAD_HR_ACTION_BY         VARCHAR(100) NULL,
    CHRO_ACTION_BY            VARCHAR(100) NULL,
    SUPER_ADMIN_ACTION_BY     VARCHAR(100) NULL,
    HR_ACTION_AT              TIMESTAMP NULL,
    HEAD_HR_ACTION_AT         TIMESTAMP NULL,
    CHRO_ACTION_AT            TIMESTAMP NULL,
    SUPER_ADMIN_ACTION_AT     TIMESTAMP NULL,
    CREATED_AT                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ERM_EMP_PROFILE_REQ_EMPLOYEE ON ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS (EMPLOYEE_USER_ID);
CREATE INDEX IDX_ERM_EMP_PROFILE_REQ_STAGE ON ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS (WORKFLOW_STAGE);
