-- Add current-state columns (no AFTER chains within same statement to avoid MySQL parsing error)
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD COLUMN CURRENT_DESIGNATION_ROLE_NAME VARCHAR(100) NULL AFTER CURRENT_EMPLOYMENT_STATUS,
    ADD COLUMN CURRENT_REPORTING_MANAGER_USER_ID BIGINT NULL,
    ADD COLUMN CURRENT_REPORTING_MANAGER_NAME VARCHAR(150) NULL;

-- Add requested-state columns separately so AFTER reference resolves correctly
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD COLUMN REQUESTED_DESIGNATION_ROLE_NAME VARCHAR(100) NULL AFTER REQUESTED_EMPLOYMENT_STATUS,
    ADD COLUMN REQUESTED_REPORTING_MANAGER_USER_ID BIGINT NULL,
    ADD COLUMN REQUESTED_REPORTING_MANAGER_NAME VARCHAR(150) NULL;

-- Seed default values for any existing rows so NOT NULL constraint can be applied
UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
SET CURRENT_DESIGNATION_ROLE_NAME = 'Employee'
WHERE CURRENT_DESIGNATION_ROLE_NAME IS NULL;

UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
SET REQUESTED_DESIGNATION_ROLE_NAME = CURRENT_DESIGNATION_ROLE_NAME
WHERE REQUESTED_DESIGNATION_ROLE_NAME IS NULL;

-- Enforce NOT NULL now that all rows have values
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    MODIFY COLUMN CURRENT_DESIGNATION_ROLE_NAME VARCHAR(100) NOT NULL,
    MODIFY COLUMN REQUESTED_DESIGNATION_ROLE_NAME VARCHAR(100) NOT NULL;
