CREATE TABLE ERM_LEAVE_POLICIES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LEAVE_CATEGORY VARCHAR(30) NOT NULL UNIQUE,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    MAX_DAYS_PER_YEAR INT NOT NULL,
    IS_ENABLED TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ERM_LEAVE_REQUESTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_USER_ID BIGINT NOT NULL,
    EMPLOYEE_USERNAME VARCHAR(100) NOT NULL,
    EMPLOYEE_FULL_NAME VARCHAR(150) NOT NULL,
    LEAVE_CATEGORY VARCHAR(30) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    REQUESTED_DAYS INT NOT NULL,
    REASON VARCHAR(500) NOT NULL,
    REQUEST_STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_LEAVE_REQUESTS_USER FOREIGN KEY (EMPLOYEE_USER_ID) REFERENCES ERM_USERS (ID)
);

CREATE INDEX IDX_ERM_LEAVE_REQUESTS_USER ON ERM_LEAVE_REQUESTS (EMPLOYEE_USER_ID);
CREATE INDEX IDX_ERM_LEAVE_REQUESTS_STATUS ON ERM_LEAVE_REQUESTS (REQUEST_STATUS);
CREATE INDEX IDX_ERM_LEAVE_REQUESTS_CATEGORY ON ERM_LEAVE_REQUESTS (LEAVE_CATEGORY);

INSERT INTO ERM_LEAVE_POLICIES (LEAVE_CATEGORY, DISPLAY_NAME, MAX_DAYS_PER_YEAR, IS_ENABLED)
SELECT 'SICK', 'Sick Leave', 12, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_LEAVE_POLICIES WHERE LEAVE_CATEGORY = 'SICK');

INSERT INTO ERM_LEAVE_POLICIES (LEAVE_CATEGORY, DISPLAY_NAME, MAX_DAYS_PER_YEAR, IS_ENABLED)
SELECT 'CASUAL', 'Casual Leave', 12, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_LEAVE_POLICIES WHERE LEAVE_CATEGORY = 'CASUAL');

INSERT INTO ERM_LEAVE_POLICIES (LEAVE_CATEGORY, DISPLAY_NAME, MAX_DAYS_PER_YEAR, IS_ENABLED)
SELECT 'EARNED', 'Earned Leave', 18, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_LEAVE_POLICIES WHERE LEAVE_CATEGORY = 'EARNED');
