INSERT INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER, IS_ACTIVE)
SELECT 'leave-policy', 'Leave Policy', '/leave-policy', 'clipboard-list', 6, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_NAV_MENUS WHERE MENU_CODE = 'leave-policy');

UPDATE ERM_NAV_MENUS
SET SORT_ORDER = SORT_ORDER + 1
WHERE MENU_CODE = 'settings'
  AND EXISTS (SELECT 1 FROM ERM_NAV_MENUS WHERE MENU_CODE = 'leave-policy');

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'leave-policy'
WHERE r.ROLE_NAME = 'HR Head';
