ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN APPROVER_MANAGER_USER_ID BIGINT NULL AFTER EMPLOYEE_FULL_NAME;

ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN APPROVER_MANAGER_USERNAME VARCHAR(100) NULL AFTER APPROVER_MANAGER_USER_ID;

ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN APPROVER_MANAGER_FULL_NAME VARCHAR(150) NULL AFTER APPROVER_MANAGER_USERNAME;

ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN APPROVER_COMMENT VARCHAR(500) NULL AFTER REQUEST_STATUS;

ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN APPROVER_ACTION_AT TIMESTAMP NULL AFTER APPROVER_COMMENT;

CREATE INDEX IDX_ERM_LEAVE_REQUESTS_APPROVER ON ERM_LEAVE_REQUESTS (APPROVER_MANAGER_USER_ID);

ALTER TABLE ERM_LEAVE_REQUESTS
    ADD CONSTRAINT FK_ERM_LEAVE_REQUESTS_APPROVER_USER
        FOREIGN KEY (APPROVER_MANAGER_USER_ID) REFERENCES ERM_USERS (ID);

UPDATE ERM_LEAVE_REQUESTS lr
JOIN ERM_USERS e ON e.ID = lr.EMPLOYEE_USER_ID
LEFT JOIN ERM_USERS m ON m.ID = e.REPORTING_MANAGER_USER_ID
SET lr.APPROVER_MANAGER_USER_ID = e.REPORTING_MANAGER_USER_ID,
    lr.APPROVER_MANAGER_USERNAME = m.USERNAME,
    lr.APPROVER_MANAGER_FULL_NAME = m.FULL_NAME
WHERE lr.APPROVER_MANAGER_USER_ID IS NULL;
