INSERT INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER, IS_ACTIVE)
SELECT 'role-audit', 'Role Audit', '/role-audit', 'shield-check', 8, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_NAV_MENUS WHERE MENU_CODE = 'role-audit');

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'role-audit'
WHERE r.ROLE_NAME IN ('Super Admin');
