CREATE TABLE ERM_ROLES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL UNIQUE,
    ROLE_DESCRIPTION VARCHAR(255) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ERM_USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ERM_USER_ROLES (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_ERM_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES ERM_USERS (ID),
    CONSTRAINT FK_ERM_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ERM_ROLES (ID)
);

CREATE TABLE ERM_TOKEN_BLACKLIST (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TOKEN_HASH VARCHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ERM_TOKEN_BLACKLIST_EXPIRES_AT ON ERM_TOKEN_BLACKLIST (EXPIRES_AT);