ALTER TABLE ERM_USERS
    ADD COLUMN PRIMARY_ROLE_ID BIGINT NULL AFTER REPORTING_MANAGER_ROLE_NAME;

UPDATE ERM_USERS u
JOIN (
    SELECT ur.USER_ID, MIN(ur.ROLE_ID) AS PRIMARY_ROLE_ID
    FROM ERM_USER_ROLES ur
    GROUP BY ur.USER_ID
) role_map ON role_map.USER_ID = u.ID
SET u.PRIMARY_ROLE_ID = role_map.PRIMARY_ROLE_ID
WHERE u.PRIMARY_ROLE_ID IS NULL;

ALTER TABLE ERM_USERS
    ADD CONSTRAINT FK_ERM_USERS_PRIMARY_ROLE
        FOREIGN KEY (PRIMARY_ROLE_ID) REFERENCES ERM_ROLES (ID);
