-- Add reminder tracking columns to ERM_ONBOARDING_REQUESTS
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN LAST_REMINDER_AT DATETIME NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN REMINDER_COUNT INT NOT NULL DEFAULT 0;
