ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN REFER_BACK_BY VARCHAR(100) NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN REFER_BACK_AT DATETIME NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN REFER_BACK_COMMENT VARCHAR(500) NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN REFER_BACK_STAGE VARCHAR(100) NULL;
