CREATE TABLE ERM_ONBOARDING_REQUEST_COMMENTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ONBOARDING_REQUEST_ID BIGINT NOT NULL,
    STEP VARCHAR(120) NOT NULL,
    ACTOR VARCHAR(100) NOT NULL,
    DECISION VARCHAR(50) NOT NULL,
    COMMENT_TEXT VARCHAR(500) NULL,
    ACTION_AT DATETIME NOT NULL,
    CONSTRAINT FK_ERM_ONBOARDING_REQUEST_COMMENTS_REQUEST
        FOREIGN KEY (ONBOARDING_REQUEST_ID) REFERENCES ERM_ONBOARDING_REQUESTS (ID)
);

CREATE INDEX IDX_ERM_ONBOARDING_REQUEST_COMMENTS_REQ_TIME
    ON ERM_ONBOARDING_REQUEST_COMMENTS (ONBOARDING_REQUEST_ID, ACTION_AT, ID);
