CREATE TABLE ERM_PROJECT_REQUESTS
(
    ID                     BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_NAME           VARCHAR(150)  NOT NULL,
    PROJECT_CODE           VARCHAR(30)   NOT NULL UNIQUE,
    CLIENT_NAME            VARCHAR(150)  NOT NULL,
    PROJECT_TYPE           VARCHAR(40)   NOT NULL,
    PRIORITY               VARCHAR(20)   NOT NULL,
    PLANNED_START_DATE     DATE          NOT NULL,
    PLANNED_END_DATE       DATE          NOT NULL,
    BUDGET_AMOUNT          DECIMAL(15,2) NOT NULL,
    CURRENCY               VARCHAR(10)   NOT NULL,
    DELIVERY_MANAGER_USER_ID BIGINT      NOT NULL,
    DELIVERY_MANAGER_NAME  VARCHAR(150)  NOT NULL,
    DESCRIPTION            VARCHAR(2000) NOT NULL,
    RISK_NOTES             VARCHAR(1000) NULL,
    WORKFLOW_STAGE         VARCHAR(50)   NOT NULL DEFAULT 'PM_SUBMITTED',
    CREATED_BY_USERNAME    VARCHAR(100)  NOT NULL,
    DM_ACTION_BY           VARCHAR(100)  NULL,
    DM_ACTION_AT           TIMESTAMP     NULL,
    DM_COMMENT             VARCHAR(500)  NULL,
    CTO_ACTION_BY          VARCHAR(100)  NULL,
    CTO_ACTION_AT          TIMESTAMP     NULL,
    CTO_COMMENT            VARCHAR(500)  NULL,
    SUPER_ADMIN_ACTION_BY  VARCHAR(100)  NULL,
    SUPER_ADMIN_ACTION_AT  TIMESTAMP     NULL,
    SUPER_ADMIN_COMMENT    VARCHAR(500)  NULL,
    REFER_BACK_BY          VARCHAR(100)  NULL,
    REFER_BACK_AT          TIMESTAMP     NULL,
    REFER_BACK_COMMENT     VARCHAR(500)  NULL,
    REFER_BACK_STAGE       VARCHAR(100)  NULL,
    VERSION                BIGINT        NOT NULL DEFAULT 0,
    CREATED_AT             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ERM_PROJECT_REQUEST_COMMENTS
(
    ID                 BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_REQUEST_ID BIGINT       NOT NULL,
    STEP               VARCHAR(120) NOT NULL,
    ACTOR              VARCHAR(100) NOT NULL,
    DECISION           VARCHAR(50)  NOT NULL,
    COMMENT_TEXT       VARCHAR(500) NULL,
    ACTION_AT          TIMESTAMP    NOT NULL,
    CONSTRAINT FK_ERM_PROJECT_REQ_COMMENTS_REQ
        FOREIGN KEY (PROJECT_REQUEST_ID) REFERENCES ERM_PROJECT_REQUESTS (ID)
);

CREATE INDEX IDX_ERM_PROJECT_REQ_STAGE ON ERM_PROJECT_REQUESTS (WORKFLOW_STAGE);
CREATE INDEX IDX_ERM_PROJECT_REQ_CREATOR ON ERM_PROJECT_REQUESTS (CREATED_BY_USERNAME);
CREATE INDEX IDX_ERM_PROJECT_REQ_CODE ON ERM_PROJECT_REQUESTS (PROJECT_CODE);
CREATE INDEX IDX_ERM_PROJECT_REQ_DM ON ERM_PROJECT_REQUESTS (DELIVERY_MANAGER_USER_ID);
CREATE INDEX IDX_ERM_PROJECT_REQ_UPDATED ON ERM_PROJECT_REQUESTS (UPDATED_AT);
CREATE INDEX IDX_ERM_PROJECT_REQ_COMMENTS_REQ_TIME
    ON ERM_PROJECT_REQUEST_COMMENTS (PROJECT_REQUEST_ID, ACTION_AT, ID);
