CREATE TABLE ERM_PROJECT_ALLOCATIONS
(
    ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    ALLOCATION_CODE     VARCHAR(40)   NOT NULL UNIQUE,
    PROJECT_REQUEST_ID  BIGINT        NOT NULL,
    PROJECT_NAME        VARCHAR(150)  NOT NULL,
    PROJECT_CODE        VARCHAR(30)   NOT NULL,
    EMPLOYEE_USER_ID    BIGINT        NOT NULL,
    EMPLOYEE_NAME       VARCHAR(150)  NOT NULL,
    EMPLOYEE_ROLE_NAME  VARCHAR(100)  NULL,
    ALLOCATION_TYPE     VARCHAR(30)   NOT NULL,
    ALLOCATION_PERCENT  DECIMAL(5,2)  NOT NULL,
    START_DATE          DATE          NOT NULL,
    END_DATE            DATE          NOT NULL,
    STATUS              VARCHAR(40)   NOT NULL DEFAULT 'PENDING_DM_APPROVAL',
    CREATED_BY_USERNAME VARCHAR(100)  NOT NULL,
    DM_ACTION_BY        VARCHAR(100)  NULL,
    DM_ACTION_AT        TIMESTAMP     NULL,
    DM_COMMENT          VARCHAR(500)  NULL,
    REFER_BACK_BY       VARCHAR(100)  NULL,
    REFER_BACK_AT       TIMESTAMP     NULL,
    REFER_BACK_COMMENT  VARCHAR(500)  NULL,
    VERSION             BIGINT        NOT NULL DEFAULT 0,
    CREATED_AT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_PROJ_ALLOC_REQ
        FOREIGN KEY (PROJECT_REQUEST_ID) REFERENCES ERM_PROJECT_REQUESTS (ID),
    CONSTRAINT FK_ERM_PROJ_ALLOC_USER
        FOREIGN KEY (EMPLOYEE_USER_ID) REFERENCES ERM_USERS (ID)
);

CREATE TABLE ERM_PROJECT_ALLOCATION_COMMENTS
(
    ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_ALLOCATION_ID BIGINT       NOT NULL,
    STEP                  VARCHAR(120) NOT NULL,
    ACTOR                 VARCHAR(100) NOT NULL,
    DECISION              VARCHAR(50)  NOT NULL,
    COMMENT_TEXT          VARCHAR(500) NULL,
    ACTION_AT             TIMESTAMP    NOT NULL,
    CONSTRAINT FK_ERM_PROJ_ALLOC_COMMENTS_ALLOC
        FOREIGN KEY (PROJECT_ALLOCATION_ID) REFERENCES ERM_PROJECT_ALLOCATIONS (ID)
);

CREATE INDEX IDX_ERM_PROJ_ALLOC_STATUS ON ERM_PROJECT_ALLOCATIONS (STATUS);
CREATE INDEX IDX_ERM_PROJ_ALLOC_EMP_DATES ON ERM_PROJECT_ALLOCATIONS (EMPLOYEE_USER_ID, START_DATE, END_DATE);
CREATE INDEX IDX_ERM_PROJ_ALLOC_PROJECT ON ERM_PROJECT_ALLOCATIONS (PROJECT_REQUEST_ID);
CREATE INDEX IDX_ERM_PROJ_ALLOC_CREATOR ON ERM_PROJECT_ALLOCATIONS (CREATED_BY_USERNAME);
CREATE INDEX IDX_ERM_PROJ_ALLOC_UPDATED ON ERM_PROJECT_ALLOCATIONS (UPDATED_AT);
CREATE INDEX IDX_ERM_PROJ_ALLOC_COMMENTS_TIME
    ON ERM_PROJECT_ALLOCATION_COMMENTS (PROJECT_ALLOCATION_ID, ACTION_AT, ID);
