ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD COLUMN REPLACEMENT_TEAM_LEAD_USER_ID BIGINT NULL,
    ADD COLUMN REPLACEMENT_TEAM_LEAD_NAME VARCHAR(150) NULL,
    ADD COLUMN DIRECT_REPORTS_AFFECTED_COUNT INT NOT NULL DEFAULT 0;

CREATE INDEX IDX_ERM_EMP_PROFILE_UPD_REPL_TL_USER_ID
    ON ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS (REPLACEMENT_TEAM_LEAD_USER_ID);
