CREATE TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUEST_COMMENTS
(
    ID                               BIGINT PRIMARY KEY AUTO_INCREMENT,
    EMPLOYEE_PROFILE_UPDATE_REQUEST_ID BIGINT       NOT NULL,
    STEP                             VARCHAR(120) NOT NULL,
    ACTOR                            VARCHAR(100) NOT NULL,
    DECISION                         VARCHAR(50)  NOT NULL,
    COMMENT_TEXT                     VARCHAR(500) NULL,
    ACTION_AT                        TIMESTAMP    NOT NULL,
    CREATED_AT                       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ERM_EMP_PROFILE_UPD_COMMENTS_REQ_ID
    ON ERM_EMPLOYEE_PROFILE_UPDATE_REQUEST_COMMENTS (EMPLOYEE_PROFILE_UPDATE_REQUEST_ID, ACTION_AT, ID);
