ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN PROJECT_OWNER_USER_ID BIGINT NULL,
    ADD COLUMN PROJECT_OWNER_NAME VARCHAR(150) NULL,
    ADD COLUMN PROJECT_STATUS VARCHAR(30) NOT NULL DEFAULT 'PLANNED';

ALTER TABLE ERM_PROJECT_REQUESTS
    ADD CONSTRAINT FK_ERM_PROJECT_REQ_OWNER
        FOREIGN KEY (PROJECT_OWNER_USER_ID) REFERENCES ERM_USERS (ID);

UPDATE ERM_PROJECT_REQUESTS
SET PROJECT_OWNER_USER_ID = DELIVERY_MANAGER_USER_ID,
    PROJECT_OWNER_NAME = DELIVERY_MANAGER_NAME
WHERE PROJECT_OWNER_USER_ID IS NULL;

ALTER TABLE ERM_PROJECT_REQUESTS
    MODIFY COLUMN PROJECT_OWNER_USER_ID BIGINT NOT NULL,
    MODIFY COLUMN PROJECT_OWNER_NAME VARCHAR(150) NOT NULL;

CREATE TABLE ERM_PROJECT_CHANGE_REQUESTS
(
    ID                      BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_REQUEST_ID      BIGINT         NOT NULL,
    PROJECT_NAME            VARCHAR(150)   NOT NULL,
    PROJECT_CODE            VARCHAR(30)    NOT NULL,
    CLIENT_NAME             VARCHAR(150)   NOT NULL,
    PROJECT_TYPE            VARCHAR(40)    NOT NULL,
    PRIORITY                VARCHAR(20)    NOT NULL,
    PLANNED_START_DATE      DATE           NOT NULL,
    PLANNED_END_DATE        DATE           NOT NULL,
    BUDGET_AMOUNT           DECIMAL(15, 2) NOT NULL,
    CURRENCY                VARCHAR(10)    NOT NULL,
    DELIVERY_MANAGER_USER_ID BIGINT        NOT NULL,
    DELIVERY_MANAGER_NAME   VARCHAR(150)   NOT NULL,
    PROJECT_OWNER_USER_ID   BIGINT         NOT NULL,
    PROJECT_OWNER_NAME      VARCHAR(150)   NOT NULL,
    PROJECT_STATUS          VARCHAR(30)    NOT NULL DEFAULT 'PLANNED',
    DESCRIPTION             VARCHAR(2000)  NOT NULL,
    RISK_NOTES              VARCHAR(1000)  NULL,
    CHANGE_REASON           VARCHAR(500)   NOT NULL,
    WORKFLOW_STAGE          VARCHAR(50)    NOT NULL DEFAULT 'PENDING_DELIVERY_MANAGER_APPROVAL',
    CREATED_BY_USERNAME     VARCHAR(100)   NOT NULL,
    DM_ACTION_BY            VARCHAR(100)   NULL,
    DM_ACTION_AT            TIMESTAMP      NULL,
    DM_COMMENT              VARCHAR(500)   NULL,
    PROJECT_OWNER_ACTION_BY VARCHAR(100)   NULL,
    PROJECT_OWNER_ACTION_AT TIMESTAMP      NULL,
    PROJECT_OWNER_COMMENT   VARCHAR(500)   NULL,
    VERSION                 BIGINT         NOT NULL DEFAULT 0,
    CREATED_AT              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_PROJECT_CHANGE_REQ_PROJECT
        FOREIGN KEY (PROJECT_REQUEST_ID) REFERENCES ERM_PROJECT_REQUESTS (ID),
    CONSTRAINT FK_ERM_PROJECT_CHANGE_REQ_DM
        FOREIGN KEY (DELIVERY_MANAGER_USER_ID) REFERENCES ERM_USERS (ID),
    CONSTRAINT FK_ERM_PROJECT_CHANGE_REQ_OWNER
        FOREIGN KEY (PROJECT_OWNER_USER_ID) REFERENCES ERM_USERS (ID)
);

CREATE TABLE ERM_PROJECT_CHANGE_REQUEST_COMMENTS
(
    ID                        BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_CHANGE_REQUEST_ID BIGINT       NOT NULL,
    STEP                      VARCHAR(120) NOT NULL,
    ACTOR                     VARCHAR(100) NOT NULL,
    DECISION                  VARCHAR(50)  NOT NULL,
    COMMENT_TEXT              VARCHAR(500) NULL,
    ACTION_AT                 TIMESTAMP    NOT NULL,
    CONSTRAINT FK_ERM_PROJECT_CHANGE_REQ_COMMENT
        FOREIGN KEY (PROJECT_CHANGE_REQUEST_ID) REFERENCES ERM_PROJECT_CHANGE_REQUESTS (ID)
);

CREATE INDEX IDX_ERM_PROJECT_CHANGE_PROJECT ON ERM_PROJECT_CHANGE_REQUESTS (PROJECT_REQUEST_ID);
CREATE INDEX IDX_ERM_PROJECT_CHANGE_STAGE ON ERM_PROJECT_CHANGE_REQUESTS (WORKFLOW_STAGE);
CREATE INDEX IDX_ERM_PROJECT_CHANGE_CREATOR ON ERM_PROJECT_CHANGE_REQUESTS (CREATED_BY_USERNAME);
CREATE INDEX IDX_ERM_PROJECT_CHANGE_CREATED ON ERM_PROJECT_CHANGE_REQUESTS (CREATED_AT);
CREATE INDEX IDX_ERM_PROJECT_CHANGE_COMMENT_TIME
    ON ERM_PROJECT_CHANGE_REQUEST_COMMENTS (PROJECT_CHANGE_REQUEST_ID, ACTION_AT, ID);
