ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_USER_ID BIGINT NULL AFTER PROJECT_OWNER_NAME;

ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_NAME VARCHAR(150) NULL AFTER PROJECT_DIRECTOR_USER_ID;

CREATE INDEX IF NOT EXISTS IDX_ERM_PROJECT_REQ_DIRECTOR ON ERM_PROJECT_REQUESTS (PROJECT_DIRECTOR_USER_ID);

UPDATE ERM_PROJECT_REQUESTS pr
JOIN (
    SELECT u.ID AS USER_ID,
           COALESCE(NULLIF(TRIM(u.FULL_NAME), ''), u.USERNAME) AS DISPLAY_NAME
    FROM ERM_USERS u
    JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
    JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
    WHERE LOWER(r.ROLE_NAME) = 'director'
      AND u.IS_ACTIVE = 1
      AND LOWER(u.EMPLOYMENT_STATUS) = 'active'
    ORDER BY u.ID
    LIMIT 1
) d
SET pr.PROJECT_DIRECTOR_USER_ID = d.USER_ID,
    pr.PROJECT_DIRECTOR_NAME = d.DISPLAY_NAME
WHERE pr.PROJECT_DIRECTOR_USER_ID IS NULL;
