ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_MANAGER_USER_ID BIGINT NULL AFTER PROJECT_DIRECTOR_NAME;

ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_MANAGER_NAME VARCHAR(150) NULL AFTER PROJECT_MANAGER_USER_ID;

CREATE INDEX IF NOT EXISTS IDX_ERM_PROJECT_REQ_PM ON ERM_PROJECT_REQUESTS (PROJECT_MANAGER_USER_ID);

UPDATE ERM_PROJECT_REQUESTS pr
JOIN ERM_USERS u ON LOWER(u.USERNAME) = LOWER(pr.CREATED_BY_USERNAME)
SET pr.PROJECT_MANAGER_USER_ID = u.ID,
    pr.PROJECT_MANAGER_NAME = COALESCE(NULLIF(TRIM(u.FULL_NAME), ''), u.USERNAME)
WHERE pr.PROJECT_MANAGER_USER_ID IS NULL;
