ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_USER_ID BIGINT NULL AFTER PROJECT_OWNER_NAME;

ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_NAME VARCHAR(150) NULL AFTER PROJECT_DIRECTOR_USER_ID;

CREATE INDEX IF NOT EXISTS IDX_ERM_PROJECT_CHANGE_DIRECTOR ON ERM_PROJECT_CHANGE_REQUESTS (PROJECT_DIRECTOR_USER_ID);

UPDATE ERM_PROJECT_CHANGE_REQUESTS c
JOIN ERM_PROJECT_REQUESTS p ON p.ID = c.PROJECT_REQUEST_ID
SET c.PROJECT_DIRECTOR_USER_ID = p.PROJECT_DIRECTOR_USER_ID,
    c.PROJECT_DIRECTOR_NAME = p.PROJECT_DIRECTOR_NAME
WHERE c.PROJECT_DIRECTOR_USER_ID IS NULL;
