-- =============================================================================
-- V36: Support portal foundation
-- Creates support queues, catalog, priority matrix, SLA rules, tickets,
-- audit/notification tables, and seeds support roles/designations + menu access.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Support navigation menu
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER, IS_ACTIVE)
VALUES ('support', 'Support', '/support', 'headset', 7, 1);

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'support';

-- ---------------------------------------------------------------------------
-- 2. Support catalog and queues
-- ---------------------------------------------------------------------------
CREATE TABLE ERM_SUPPORT_CATEGORIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_CODE VARCHAR(100) NOT NULL UNIQUE,
    CATEGORY_TITLE VARCHAR(120) NOT NULL,
    TICKET_TYPE VARCHAR(50) NOT NULL,
    PARENT_CATEGORY_CODE VARCHAR(100) NULL,
    SORT_ORDER INT NOT NULL DEFAULT 0,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ERM_SUPPORT_QUEUES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUEUE_CODE VARCHAR(100) NOT NULL UNIQUE,
    QUEUE_TITLE VARCHAR(120) NOT NULL,
    QUEUE_TYPE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ERM_SUPPORT_QUEUE_MEMBERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUEUE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    LAST_ASSIGNED_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_SUPPORT_QUEUE_MEMBERS_QUEUE FOREIGN KEY (QUEUE_ID) REFERENCES ERM_SUPPORT_QUEUES (ID),
    CONSTRAINT FK_ERM_SUPPORT_QUEUE_MEMBERS_USER FOREIGN KEY (USER_ID) REFERENCES ERM_USERS (ID),
    UNIQUE KEY UK_ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID)
);

CREATE TABLE ERM_SUPPORT_PRIORITY_MATRIX (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMPACT_LEVEL VARCHAR(20) NOT NULL,
    URGENCY_LEVEL VARCHAR(20) NOT NULL,
    PRIORITY_CODE VARCHAR(20) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_ERM_SUPPORT_PRIORITY_MATRIX (IMPACT_LEVEL, URGENCY_LEVEL)
);

CREATE TABLE ERM_SUPPORT_SLA_POLICIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUEUE_CODE VARCHAR(100) NOT NULL,
    TICKET_TYPE VARCHAR(50) NOT NULL,
    PRIORITY_CODE VARCHAR(20) NOT NULL,
    RESPONSE_MINUTES INT NOT NULL,
    RESOLUTION_MINUTES INT NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE)
);

CREATE TABLE ERM_SUPPORT_ESCALATION_RULES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUEUE_CODE VARCHAR(100) NOT NULL,
    PRIORITY_CODE VARCHAR(20) NOT NULL,
    WARN_MINUTES INT NOT NULL,
    BREACH_MINUTES INT NOT NULL,
    ESCALATE_TO_ROLE_NAME VARCHAR(100) NOT NULL,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE)
);

INSERT INTO ERM_SUPPORT_CATEGORIES (CATEGORY_CODE, CATEGORY_TITLE, TICKET_TYPE, PARENT_CATEGORY_CODE, SORT_ORDER, IS_ACTIVE) VALUES
('account-access', 'Account Access', 'SUPPORT_TICKET', NULL, 10, 1),
('application-issue', 'Application Issue', 'INCIDENT', NULL, 20, 1),
('hardware-request', 'Hardware Request', 'SUPPORT_TICKET', NULL, 30, 1),
('software-access', 'Software Access', 'SUPPORT_TICKET', NULL, 40, 1),
('security-incident', 'Security Incident', 'SECURITY_INCIDENT', NULL, 50, 1);

INSERT INTO ERM_SUPPORT_QUEUES (QUEUE_CODE, QUEUE_TITLE, QUEUE_TYPE, DESCRIPTION, IS_ACTIVE) VALUES
('support', 'Support Queue', 'SUPPORT_TICKET', 'General employee support queue', 1),
('incident', 'Incident Queue', 'INCIDENT', 'Operational incident queue', 1),
('security', 'Security Queue', 'SECURITY_INCIDENT', 'Security incident queue', 1);

INSERT INTO ERM_SUPPORT_PRIORITY_MATRIX (IMPACT_LEVEL, URGENCY_LEVEL, PRIORITY_CODE, IS_ACTIVE) VALUES
('Critical', 'Critical', 'P1', 1),
('Critical', 'High', 'P1', 1),
('Critical', 'Medium', 'P2', 1),
('Critical', 'Low', 'P2', 1),
('High', 'Critical', 'P1', 1),
('High', 'High', 'P2', 1),
('High', 'Medium', 'P2', 1),
('High', 'Low', 'P3', 1),
('Medium', 'Critical', 'P2', 1),
('Medium', 'High', 'P3', 1),
('Medium', 'Medium', 'P3', 1),
('Medium', 'Low', 'P4', 1),
('Low', 'Critical', 'P3', 1),
('Low', 'High', 'P4', 1),
('Low', 'Medium', 'P4', 1),
('Low', 'Low', 'P4', 1);

INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE) VALUES
('support', 'SUPPORT_TICKET', 'P1', 15, 240, 1),
('support', 'SUPPORT_TICKET', 'P2', 30, 480, 1),
('support', 'SUPPORT_TICKET', 'P3', 60, 1440, 1),
('support', 'SUPPORT_TICKET', 'P4', 120, 2880, 1),
('incident', 'INCIDENT', 'P1', 10, 120, 1),
('incident', 'INCIDENT', 'P2', 20, 240, 1),
('incident', 'INCIDENT', 'P3', 30, 720, 1),
('incident', 'INCIDENT', 'P4', 60, 1440, 1),
('security', 'SECURITY_INCIDENT', 'P1', 5, 60, 1),
('security', 'SECURITY_INCIDENT', 'P2', 10, 120, 1),
('security', 'SECURITY_INCIDENT', 'P3', 15, 240, 1),
('security', 'SECURITY_INCIDENT', 'P4', 30, 480, 1);

INSERT INTO ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE, WARN_MINUTES, BREACH_MINUTES, ESCALATE_TO_ROLE_NAME, IS_ACTIVE) VALUES
('support', 'P1', 12, 15, 'IT Support Manager', 1),
('support', 'P2', 24, 30, 'IT Support Manager', 1),
('incident', 'P1', 8, 10, 'IT Support Manager', 1),
('incident', 'P2', 15, 20, 'IT Support Manager', 1),
('security', 'P1', 3, 5, 'IT Security', 1),
('security', 'P2', 8, 10, 'IT Support Manager', 1);

-- ---------------------------------------------------------------------------
-- 3. Queue memberships (reuses existing IT support demo users)
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID, IS_ACTIVE)
SELECT q.ID, u.ID, 1
FROM ERM_SUPPORT_QUEUES q
JOIN ERM_USERS u ON u.USERNAME IN ('appsupport', 'itsupportmanager', 'itsupportlead')
WHERE q.QUEUE_CODE = 'support';

INSERT IGNORE INTO ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID, IS_ACTIVE)
SELECT q.ID, u.ID, 1
FROM ERM_SUPPORT_QUEUES q
JOIN ERM_USERS u ON u.USERNAME IN ('appsupport', 'itsupportmanager', 'itsupportlead')
WHERE q.QUEUE_CODE = 'incident';

INSERT IGNORE INTO ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID, IS_ACTIVE)
SELECT q.ID, u.ID, 1
FROM ERM_SUPPORT_QUEUES q
JOIN ERM_USERS u ON u.USERNAME IN ('itsecurity', 'itsupportmanager')
WHERE q.QUEUE_CODE = 'security';

-- ---------------------------------------------------------------------------
-- 4. Support ticketing tables
-- ---------------------------------------------------------------------------
CREATE TABLE ERM_SUPPORT_TICKETS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    REQUESTER_USER_ID BIGINT NOT NULL,
    REQUESTER_USERNAME VARCHAR(100) NOT NULL,
    REQUESTER_FULL_NAME VARCHAR(150) NOT NULL,
    TICKET_TYPE VARCHAR(50) NOT NULL,
    CATEGORY_CODE VARCHAR(100) NOT NULL,
    CATEGORY_TITLE VARCHAR(120) NOT NULL,
    SUBCATEGORY_CODE VARCHAR(100) NULL,
    SUBCATEGORY_TITLE VARCHAR(120) NULL,
    IMPACT_LEVEL VARCHAR(20) NOT NULL,
    URGENCY_LEVEL VARCHAR(20) NOT NULL,
    PRIORITY_CODE VARCHAR(20) NOT NULL,
    QUEUE_ID BIGINT NOT NULL,
    QUEUE_CODE VARCHAR(100) NOT NULL,
    QUEUE_TITLE VARCHAR(120) NOT NULL,
    ASSIGNEE_USER_ID BIGINT NULL,
    ASSIGNEE_USERNAME VARCHAR(100) NULL,
    ASSIGNEE_FULL_NAME VARCHAR(150) NULL,
    STATUS VARCHAR(50) NOT NULL,
    SOURCE VARCHAR(50) NOT NULL,
    SHORT_DESCRIPTION VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SECURITY_INCIDENT TINYINT(1) NOT NULL DEFAULT 0,
    RESPONSE_DUE_AT TIMESTAMP NULL,
    RESOLUTION_DUE_AT TIMESTAMP NULL,
    FIRST_RESPONSE_AT TIMESTAMP NULL,
    RESOLVED_AT TIMESTAMP NULL,
    CLOSED_AT TIMESTAMP NULL,
    CREATED_BY_USERNAME VARCHAR(100) NOT NULL,
    UPDATED_BY_USERNAME VARCHAR(100) NOT NULL,
    VERSION BIGINT NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_SUPPORT_TICKETS_QUEUE FOREIGN KEY (QUEUE_ID) REFERENCES ERM_SUPPORT_QUEUES (ID),
    CONSTRAINT FK_ERM_SUPPORT_TICKETS_REQUESTER FOREIGN KEY (REQUESTER_USER_ID) REFERENCES ERM_USERS (ID),
    CONSTRAINT FK_ERM_SUPPORT_TICKETS_ASSIGNEE FOREIGN KEY (ASSIGNEE_USER_ID) REFERENCES ERM_USERS (ID)
);

CREATE TABLE ERM_SUPPORT_TICKET_COMMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_ID BIGINT NOT NULL,
    ACTOR_USERNAME VARCHAR(100) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    COMMENT_TEXT VARCHAR(1000) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_SUPPORT_TICKET_COMMENTS_TICKET FOREIGN KEY (TICKET_ID) REFERENCES ERM_SUPPORT_TICKETS (ID)
);

CREATE TABLE ERM_SUPPORT_AUDIT_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_ID BIGINT NOT NULL,
    ACTOR_USERNAME VARCHAR(100) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    FROM_STATUS VARCHAR(50) NULL,
    TO_STATUS VARCHAR(50) NULL,
    DETAILS VARCHAR(1000) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_SUPPORT_AUDIT_LOG_TICKET FOREIGN KEY (TICKET_ID) REFERENCES ERM_SUPPORT_TICKETS (ID)
);

CREATE TABLE ERM_SUPPORT_NOTIFICATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_ID BIGINT NOT NULL,
    RECIPIENT_USERNAME VARCHAR(100) NOT NULL,
    CHANNEL VARCHAR(20) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    MESSAGE_TEXT VARCHAR(1000) NOT NULL,
    READ_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ERM_SUPPORT_NOTIFICATIONS_TICKET FOREIGN KEY (TICKET_ID) REFERENCES ERM_SUPPORT_TICKETS (ID)
);
