-- =============================================================================
-- V39: Align support assignment groups with requested ERM support teams
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1) Ensure requested support groups exist as queues
-- ---------------------------------------------------------------------------
INSERT INTO ERM_SUPPORT_QUEUES (QUEUE_CODE, QUEUE_TITLE, QUEUE_TYPE, DESCRIPTION, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'ERM_APP_SUPPORT', 'SUPPORT_TICKET', 'Application support group for service and application incidents', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_QUEUES WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT'
);

INSERT INTO ERM_SUPPORT_QUEUES (QUEUE_CODE, QUEUE_TITLE, QUEUE_TYPE, DESCRIPTION, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'ERM_IT_SUPPORT', 'SECURITY_INCIDENT', 'IT security support group for security incidents', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_QUEUES WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT'
);

UPDATE ERM_SUPPORT_QUEUES
SET QUEUE_TITLE = 'ERM_APP_SUPPORT',
    DESCRIPTION = 'Application support group for service and application incidents',
    IS_ACTIVE = 1
WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT';

UPDATE ERM_SUPPORT_QUEUES
SET QUEUE_TITLE = 'ERM_IT_SUPPORT',
    DESCRIPTION = 'IT security support group for security incidents',
    IS_ACTIVE = 1
WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT';

-- ---------------------------------------------------------------------------
-- 2) Seed queue memberships from roles (no hardcoded usernames)
-- ---------------------------------------------------------------------------
INSERT IGNORE INTO ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID, IS_ACTIVE)
SELECT q.ID, u.ID, 1
FROM ERM_SUPPORT_QUEUES q
         JOIN ERM_USER_ROLES ur ON 1 = 1
         JOIN ERM_USERS u ON u.ID = ur.USER_ID
         JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
WHERE UPPER(q.QUEUE_CODE) = 'ERM_APP_SUPPORT'
  AND r.ROLE_NAME IN ('Application Support Specialist', 'IT Support Lead', 'IT Support Manager')
  AND u.IS_ACTIVE = 1
  AND LOWER(u.EMPLOYMENT_STATUS) = 'active';

INSERT IGNORE INTO ERM_SUPPORT_QUEUE_MEMBERS (QUEUE_ID, USER_ID, IS_ACTIVE)
SELECT q.ID, u.ID, 1
FROM ERM_SUPPORT_QUEUES q
         JOIN ERM_USER_ROLES ur ON 1 = 1
         JOIN ERM_USERS u ON u.ID = ur.USER_ID
         JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
WHERE UPPER(q.QUEUE_CODE) = 'ERM_IT_SUPPORT'
  AND r.ROLE_NAME IN ('IT Security', 'IT Support Lead', 'IT Support Manager')
  AND u.IS_ACTIVE = 1
  AND LOWER(u.EMPLOYMENT_STATUS) = 'active';

UPDATE ERM_SUPPORT_QUEUE_MEMBERS sqm
    JOIN ERM_SUPPORT_QUEUES q ON q.ID = sqm.QUEUE_ID
    SET sqm.IS_ACTIVE = 1
WHERE UPPER(q.QUEUE_CODE) IN ('ERM_APP_SUPPORT', 'ERM_IT_SUPPORT');

-- ---------------------------------------------------------------------------
-- 3) Ensure SLA and escalation policies for new groups
-- ---------------------------------------------------------------------------
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'SUPPORT_TICKET', 'P1', 15, 240, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'SUPPORT_TICKET', 'P2', 30, 480, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'SUPPORT_TICKET', 'P3', 60, 1440, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P3'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'SUPPORT_TICKET', 'P4', 120, 2880, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P4'
);

INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'INCIDENT', 'P1', 10, 120, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'INCIDENT', 'P2', 20, 240, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'INCIDENT', 'P3', 30, 720, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P3'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'INCIDENT', 'P4', 60, 1440, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P4'
);

INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SECURITY_INCIDENT', 'P1', 5, 60, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SECURITY_INCIDENT' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SECURITY_INCIDENT', 'P2', 10, 120, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SECURITY_INCIDENT' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SECURITY_INCIDENT', 'P3', 15, 240, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SECURITY_INCIDENT' AND PRIORITY_CODE = 'P3'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SECURITY_INCIDENT', 'P4', 30, 480, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SECURITY_INCIDENT' AND PRIORITY_CODE = 'P4'
);

INSERT INTO ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE, WARN_MINUTES, BREACH_MINUTES, ESCALATE_TO_ROLE_NAME, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'P1', 12, 15, 'IT Support Manager', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_ESCALATION_RULES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE, WARN_MINUTES, BREACH_MINUTES, ESCALATE_TO_ROLE_NAME, IS_ACTIVE)
SELECT 'ERM_APP_SUPPORT', 'P2', 24, 30, 'IT Support Manager', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_ESCALATION_RULES
    WHERE UPPER(QUEUE_CODE) = 'ERM_APP_SUPPORT' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE, WARN_MINUTES, BREACH_MINUTES, ESCALATE_TO_ROLE_NAME, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'P1', 3, 5, 'IT Security', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_ESCALATION_RULES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_ESCALATION_RULES (QUEUE_CODE, PRIORITY_CODE, WARN_MINUTES, BREACH_MINUTES, ESCALATE_TO_ROLE_NAME, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'P2', 8, 10, 'IT Support Manager', 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_ESCALATION_RULES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND PRIORITY_CODE = 'P2'
);
