CREATE TABLE ERM_ONBOARDING_REQUESTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    AADHAAR_CARD_NUMBER VARCHAR(12) NOT NULL UNIQUE,
    PAN_CARD_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    PERSONAL_EMAIL_ADDRESS VARCHAR(150) NOT NULL,
    PERMANENT_ADDRESS VARCHAR(500) NOT NULL,
    PHONE_NUMBER VARCHAR(25) NOT NULL,
    EDUCATION_QUALIFICATION VARCHAR(255) NULL,
    INTERVIEW_STAGE VARCHAR(20) NOT NULL,
    GENERATED_EMPLOYEE_ID VARCHAR(50) UNIQUE NULL,
    GENERATED_EMAIL_ADDRESS VARCHAR(150) UNIQUE NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_ERM_ONBOARDING_REQUESTS_STAGE ON ERM_ONBOARDING_REQUESTS (INTERVIEW_STAGE);