-- =============================================================================
-- V40: Add missing SLA policies for ERM_IT_SUPPORT non-security tickets
-- =============================================================================

-- SUPPORT_TICKET
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SUPPORT_TICKET', 'P1', 15, 240, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SUPPORT_TICKET', 'P2', 30, 480, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SUPPORT_TICKET', 'P3', 60, 1440, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P3'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'SUPPORT_TICKET', 'P4', 120, 2880, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'SUPPORT_TICKET' AND PRIORITY_CODE = 'P4'
);

-- INCIDENT
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'INCIDENT', 'P1', 10, 120, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P1'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'INCIDENT', 'P2', 20, 240, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P2'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'INCIDENT', 'P3', 30, 720, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P3'
);
INSERT INTO ERM_SUPPORT_SLA_POLICIES (QUEUE_CODE, TICKET_TYPE, PRIORITY_CODE, RESPONSE_MINUTES, RESOLUTION_MINUTES, IS_ACTIVE)
SELECT 'ERM_IT_SUPPORT', 'INCIDENT', 'P4', 60, 1440, 1
    WHERE NOT EXISTS (
    SELECT 1 FROM ERM_SUPPORT_SLA_POLICIES
    WHERE UPPER(QUEUE_CODE) = 'ERM_IT_SUPPORT' AND UPPER(TICKET_TYPE) = 'INCIDENT' AND PRIORITY_CODE = 'P4'
);
