-- Store GitHub comments and issue activity in the support ticket timeline.
ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    MODIFY COLUMN COMMENT_TEXT MEDIUMTEXT NULL;

ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    ADD COLUMN GITHUB_COMMENT_ID BIGINT NULL;

ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    ADD COLUMN GITHUB_DELIVERY_ID VARCHAR(100) NULL;

ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    ADD CONSTRAINT UK_ERM_SUPPORT_TICKET_COMMENTS_GITHUB_ID UNIQUE (GITHUB_COMMENT_ID);

ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    ADD CONSTRAINT UK_ERM_SUPPORT_TICKET_COMMENTS_GITHUB_DELIVERY UNIQUE (GITHUB_DELIVERY_ID);
