-- Store GitHub comments and issue activity in the support ticket timeline.
ALTER TABLE ERM_SUPPORT_TICKET_COMMENTS
    MODIFY COLUMN COMMENT_TEXT MEDIUMTEXT NULL,
    ADD COLUMN GITHUB_COMMENT_ID BIGINT NULL,
    ADD COLUMN GITHUB_DELIVERY_ID VARCHAR(100) NULL,
    ADD CONSTRAINT UK_ERM_SUPPORT_TICKET_COMMENTS_GITHUB_ID UNIQUE (GITHUB_COMMENT_ID),
    ADD CONSTRAINT UK_ERM_SUPPORT_TICKET_COMMENTS_GITHUB_DELIVERY UNIQUE (GITHUB_DELIVERY_ID);
