-- Role-specific employee ID formats and a deterministic backfill for existing users.
CREATE TABLE IF NOT EXISTS ERM_EMPLOYEE_ID_ROLE_FORMATS (
    ROLE_NAME VARCHAR(100) NOT NULL PRIMARY KEY,
    ID_PREFIX VARCHAR(20) NOT NULL,
    SEQUENCE_ENABLED TINYINT(1) NOT NULL,
    PRIORITY_ORDER INT NOT NULL
);

INSERT INTO ERM_EMPLOYEE_ID_ROLE_FORMATS (ROLE_NAME, ID_PREFIX, SEQUENCE_ENABLED, PRIORITY_ORDER) VALUES
    ('Super Admin', 'ERM-SUP-ADM', 1, 1),
    ('Admin', 'ERM-ADM', 1, 2),
    ('CEO', 'ERM-CEO', 0, 3),
    ('CFO', 'ERM-CFO', 0, 4),
    ('CTO', 'ERM-CTO', 0, 5),
    ('CHRO', 'ERM-CHRO', 0, 6),
    ('HR Head', 'ERM-HR-HEAD', 1, 7),
    ('Senior HR', 'ERM-SR-HR', 1, 8),
    ('Junior HR', 'ERM-JR-HR', 1, 9),
    ('Project Owner', 'ERM-PO', 1, 10),
    ('Product Owner', 'ERM-PO', 1, 10),
    ('Program Manager', 'ERM-PM', 1, 11),
    ('Delivery Manager', 'ERM-DM', 1, 12),
    ('Project Manager', 'ERM-PMGR', 1, 13),
    ('Team Lead', 'ERM-TLEAD', 1, 14),
    ('Employee', 'ERM-EMP', 1, 15),
    ('Intern', 'ERM-INT', 1, 16),
    ('Application Support Specialist', 'ERM-APP-SEP', 1, 17),
    ('IT Security', 'ERM-IT-SEC', 1, 18),
    ('IT Support Lead', 'ERM-IT-SUP-LEAD', 1, 19),
    ('IT Support Manager', 'ERM-IT-SUP-MGR', 1, 20),
    ('Director', 'ERM-DIR', 1, 21)
ON DUPLICATE KEY UPDATE
    ID_PREFIX = VALUES(ID_PREFIX),
    SEQUENCE_ENABLED = VALUES(SEQUENCE_ENABLED),
    PRIORITY_ORDER = VALUES(PRIORITY_ORDER);

-- Older users may not have a primary role. Select one using the supplied role order.
UPDATE ERM_USERS u
SET u.PRIMARY_ROLE_ID = (
    SELECT r.ID
    FROM ERM_USER_ROLES ur
    JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
    JOIN ERM_EMPLOYEE_ID_ROLE_FORMATS f ON LOWER(f.ROLE_NAME) = LOWER(r.ROLE_NAME)
    WHERE ur.USER_ID = u.ID
    ORDER BY f.PRIORITY_ORDER
    LIMIT 1
)
WHERE u.PRIMARY_ROLE_ID IS NULL
  AND EXISTS (
      SELECT 1
      FROM ERM_USER_ROLES ur
      JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
      JOIN ERM_EMPLOYEE_ID_ROLE_FORMATS f ON LOWER(f.ROLE_NAME) = LOWER(r.ROLE_NAME)
      WHERE ur.USER_ID = u.ID
  );

-- Materialize the assignment first so existing users receive stable, unique per-role numbers.
CREATE TABLE IF NOT EXISTS ERM_EMPLOYEE_ID_BACKFILL (
    USER_ID BIGINT NOT NULL PRIMARY KEY,
    ID_PREFIX VARCHAR(20) NOT NULL,
    SEQUENCE_ENABLED TINYINT(1) NOT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL
);

TRUNCATE TABLE ERM_EMPLOYEE_ID_BACKFILL;

INSERT INTO ERM_EMPLOYEE_ID_BACKFILL (USER_ID, ID_PREFIX, SEQUENCE_ENABLED, SEQUENCE_NUMBER)
SELECT ranked.USER_ID, ranked.ID_PREFIX, ranked.SEQUENCE_ENABLED, ranked.SEQUENCE_NUMBER
FROM (
    SELECT u.ID AS USER_ID,
           COALESCE(f.ID_PREFIX, 'ERM-EMP') AS ID_PREFIX,
           COALESCE(f.SEQUENCE_ENABLED, 1) AS SEQUENCE_ENABLED,
           ROW_NUMBER() OVER (PARTITION BY COALESCE(f.ID_PREFIX, 'ERM-EMP') ORDER BY u.ID) AS SEQUENCE_NUMBER
    FROM ERM_USERS u
    LEFT JOIN ERM_ROLES r ON r.ID = u.PRIMARY_ROLE_ID
    LEFT JOIN ERM_EMPLOYEE_ID_ROLE_FORMATS f ON LOWER(f.ROLE_NAME) = LOWER(r.ROLE_NAME)
) ranked;

UPDATE ERM_USERS u
JOIN ERM_EMPLOYEE_ID_BACKFILL b ON b.USER_ID = u.ID
SET u.EMPLOYEE_ID = CASE
    WHEN b.SEQUENCE_ENABLED = 1 THEN CONCAT(b.ID_PREFIX, '-', LPAD(b.SEQUENCE_NUMBER, 2, '0'))
    ELSE b.ID_PREFIX
END;

INSERT INTO ERM_EMPLOYEE_ID_SEQUENCES (DESIGNATION_CODE, LAST_SEQUENCE)
SELECT f.ID_PREFIX, COALESCE(MAX(b.SEQUENCE_NUMBER), 0)
FROM ERM_EMPLOYEE_ID_ROLE_FORMATS f
LEFT JOIN ERM_EMPLOYEE_ID_BACKFILL b ON b.ID_PREFIX = f.ID_PREFIX AND b.SEQUENCE_ENABLED = 1
WHERE f.SEQUENCE_ENABLED = 1
GROUP BY f.ID_PREFIX
ON DUPLICATE KEY UPDATE LAST_SEQUENCE = GREATEST(LAST_SEQUENCE, VALUES(LAST_SEQUENCE));

DROP TABLE ERM_EMPLOYEE_ID_BACKFILL;
