CREATE TABLE IF NOT EXISTS ERM_MENTION_NOTIFICATIONS (
                                                         ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                                                         RECIPIENT_USERNAME VARCHAR(100) NOT NULL,
    ACTOR_USERNAME VARCHAR(100) NOT NULL,
    CONTEXT_TYPE VARCHAR(60) NOT NULL,
    CONTEXT_ID BIGINT NULL,
    MESSAGE_TEXT VARCHAR(1000) NOT NULL,
    HREF VARCHAR(255) NOT NULL,
    READ_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS IX_ERM_MENTION_NOTIFICATIONS_RECIPIENT_CREATED
    ON ERM_MENTION_NOTIFICATIONS (RECIPIENT_USERNAME, CREATED_AT DESC);
