-- Add searchable employee ID references beside the existing numeric user keys.
ALTER TABLE ERM_USERS ADD COLUMN IF NOT EXISTS REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_USER_ROLES ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_USER_BANK_DETAILS ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS
    ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS CURRENT_REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS REPLACEMENT_TEAM_LEAD_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_LEAVE_REQUESTS
    ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS APPROVER_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN IF NOT EXISTS DELIVERY_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS PROJECT_OWNER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS PROJECT_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS
    ADD COLUMN IF NOT EXISTS DELIVERY_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS PROJECT_OWNER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS PROJECT_DIRECTOR_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_PROJECT_ALLOCATIONS ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_SUPPORT_QUEUE_MEMBERS ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_SUPPORT_TICKETS
    ADD COLUMN IF NOT EXISTS REQUESTER_EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS ASSIGNEE_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN IF NOT EXISTS REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_ATTENDANCE_TIMESHEETS
    ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS APPROVER_MANAGER_EMPLOYEE_ID VARCHAR(50) NULL;
ALTER TABLE ERM_ATTENDANCE_LEAVE_RECONCILIATIONS ADD COLUMN IF NOT EXISTS EMPLOYEE_ID VARCHAR(50) NULL;

-- Backfill every reference using the existing numeric foreign key.
UPDATE ERM_USERS child JOIN ERM_USERS parent ON parent.ID = child.REPORTING_MANAGER_USER_ID
SET child.REPORTING_MANAGER_EMPLOYEE_ID = parent.EMPLOYEE_ID;
UPDATE ERM_USER_ROLES link JOIN ERM_USERS u ON u.ID = link.USER_ID SET link.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_USER_BANK_DETAILS link JOIN ERM_USERS u ON u.ID = link.USER_ID SET link.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_DESIGNATION_REQUESTS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_DESIGNATION_REQUESTS x JOIN ERM_USERS u ON u.ID = x.REQUESTED_REPORTING_MANAGER_USER_ID SET x.REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.CURRENT_REPORTING_MANAGER_USER_ID SET x.CURRENT_REPORTING_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.REQUESTED_REPORTING_MANAGER_USER_ID SET x.REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.REPLACEMENT_TEAM_LEAD_USER_ID SET x.REPLACEMENT_TEAM_LEAD_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_LEAVE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_LEAVE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.APPROVER_MANAGER_USER_ID SET x.APPROVER_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_REQUESTS x JOIN ERM_USERS u ON u.ID = x.DELIVERY_MANAGER_USER_ID SET x.DELIVERY_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_REQUESTS x JOIN ERM_USERS u ON u.ID = x.PROJECT_OWNER_USER_ID SET x.PROJECT_OWNER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_REQUESTS x JOIN ERM_USERS u ON u.ID = x.PROJECT_DIRECTOR_USER_ID SET x.PROJECT_DIRECTOR_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_REQUESTS x JOIN ERM_USERS u ON u.ID = x.PROJECT_MANAGER_USER_ID SET x.PROJECT_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_CHANGE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.DELIVERY_MANAGER_USER_ID SET x.DELIVERY_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_CHANGE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.PROJECT_OWNER_USER_ID SET x.PROJECT_OWNER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_CHANGE_REQUESTS x JOIN ERM_USERS u ON u.ID = x.PROJECT_DIRECTOR_USER_ID SET x.PROJECT_DIRECTOR_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_PROJECT_ALLOCATIONS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_SUPPORT_QUEUE_MEMBERS x JOIN ERM_USERS u ON u.ID = x.USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_SUPPORT_TICKETS x JOIN ERM_USERS u ON u.ID = x.REQUESTER_USER_ID SET x.REQUESTER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_SUPPORT_TICKETS x JOIN ERM_USERS u ON u.ID = x.ASSIGNEE_USER_ID SET x.ASSIGNEE_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_ONBOARDING_REQUESTS x JOIN ERM_USERS u ON u.ID = x.REPORTING_MANAGER_USER_ID SET x.REPORTING_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_ATTENDANCE_TIMESHEETS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_ATTENDANCE_TIMESHEETS x JOIN ERM_USERS u ON u.ID = x.APPROVER_MANAGER_USER_ID SET x.APPROVER_MANAGER_EMPLOYEE_ID = u.EMPLOYEE_ID;
UPDATE ERM_ATTENDANCE_LEAVE_RECONCILIATIONS x JOIN ERM_USERS u ON u.ID = x.EMPLOYEE_USER_ID SET x.EMPLOYEE_ID = u.EMPLOYEE_ID;

-- Preserve required-reference guarantees for required user relationships.
ALTER TABLE ERM_USER_ROLES MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_USER_BANK_DETAILS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS MODIFY COLUMN REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS MODIFY COLUMN REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_LEAVE_REQUESTS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_PROJECT_REQUESTS MODIFY COLUMN DELIVERY_MANAGER_EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_PROJECT_REQUESTS MODIFY COLUMN PROJECT_OWNER_EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_PROJECT_ALLOCATIONS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_SUPPORT_QUEUE_MEMBERS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_SUPPORT_TICKETS MODIFY COLUMN REQUESTER_EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_ATTENDANCE_TIMESHEETS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;
ALTER TABLE ERM_ATTENDANCE_LEAVE_RECONCILIATIONS MODIFY COLUMN EMPLOYEE_ID VARCHAR(50) NOT NULL;

-- Employee IDs are unique alternate keys on ERM_USERS and are enforced as real foreign keys.
ALTER TABLE ERM_USERS ADD CONSTRAINT FK_USERS_MANAGER_EMPLOYEE FOREIGN KEY (REPORTING_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_USER_ROLES ADD CONSTRAINT FK_USER_ROLES_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_USER_BANK_DETAILS ADD CONSTRAINT FK_BANK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS ADD CONSTRAINT FK_DESIGNATION_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_DESIGNATION_REQUESTS ADD CONSTRAINT FK_DESIGNATION_MANAGER_EMPLOYEE FOREIGN KEY (REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS ADD CONSTRAINT FK_PROFILE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS ADD CONSTRAINT FK_PROFILE_CURRENT_MANAGER_EID FOREIGN KEY (CURRENT_REPORTING_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS ADD CONSTRAINT FK_PROFILE_REQUESTED_MANAGER_EID FOREIGN KEY (REQUESTED_REPORTING_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS ADD CONSTRAINT FK_PROFILE_REPLACEMENT_TL_EID FOREIGN KEY (REPLACEMENT_TEAM_LEAD_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_LEAVE_REQUESTS ADD CONSTRAINT FK_LEAVE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_LEAVE_REQUESTS ADD CONSTRAINT FK_LEAVE_APPROVER_EMPLOYEE FOREIGN KEY (APPROVER_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_REQUESTS ADD CONSTRAINT FK_PROJECT_DELIVERY_MANAGER_EID FOREIGN KEY (DELIVERY_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_REQUESTS ADD CONSTRAINT FK_PROJECT_OWNER_EID FOREIGN KEY (PROJECT_OWNER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_REQUESTS ADD CONSTRAINT FK_PROJECT_DIRECTOR_EID FOREIGN KEY (PROJECT_DIRECTOR_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_REQUESTS ADD CONSTRAINT FK_PROJECT_MANAGER_EID FOREIGN KEY (PROJECT_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD CONSTRAINT FK_CHANGE_DELIVERY_MANAGER_EID FOREIGN KEY (DELIVERY_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD CONSTRAINT FK_CHANGE_OWNER_EID FOREIGN KEY (PROJECT_OWNER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD CONSTRAINT FK_CHANGE_DIRECTOR_EID FOREIGN KEY (PROJECT_DIRECTOR_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_PROJECT_ALLOCATIONS ADD CONSTRAINT FK_ALLOCATION_EMPLOYEE_EID FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_SUPPORT_QUEUE_MEMBERS ADD CONSTRAINT FK_SUPPORT_MEMBER_EMPLOYEE_EID FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_SUPPORT_TICKETS ADD CONSTRAINT FK_TICKET_REQUESTER_EMPLOYEE_EID FOREIGN KEY (REQUESTER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_SUPPORT_TICKETS ADD CONSTRAINT FK_TICKET_ASSIGNEE_EMPLOYEE_EID FOREIGN KEY (ASSIGNEE_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD CONSTRAINT FK_ONBOARDING_MANAGER_EMPLOYEE_EID FOREIGN KEY (REPORTING_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_ATTENDANCE_TIMESHEETS ADD CONSTRAINT FK_TIMESHEET_EMPLOYEE_EID FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_ATTENDANCE_TIMESHEETS ADD CONSTRAINT FK_TIMESHEET_APPROVER_EMPLOYEE_EID FOREIGN KEY (APPROVER_MANAGER_EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;
ALTER TABLE ERM_ATTENDANCE_LEAVE_RECONCILIATIONS ADD CONSTRAINT FK_ATT_RECON_EMPLOYEE_EID FOREIGN KEY (EMPLOYEE_ID) REFERENCES ERM_USERS (EMPLOYEE_ID) ON UPDATE CASCADE;

