CREATE TABLE ERM_NOTIFICATION_BANNERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    MESSAGE VARCHAR(2000) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    NOTIFICATION_TYPE VARCHAR(30) NOT NULL,
    CREATED_BY_USERNAME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_NOTIFICATION_BANNER_DATES (START_DATE, END_DATE)
);

INSERT INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER)
VALUES ('notification-banners', 'Notification Banner', '/notification-banners', 'megaphone', 13);

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'notification-banners'
WHERE r.ROLE_NAME IN ('Admin', 'Super Admin');
