INSERT IGNORE INTO ERM_USERS (USERNAME, EMAIL, PASSWORD_HASH, IS_ACTIVE) VALUES
('superadmin', 'superadmin@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('admin', 'admin@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('ceo', 'ceo@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('cfo', 'cfo@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('cto', 'cto@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('chro', 'chro@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('hrhead', 'hrhead@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('seniorhr', 'seniorhr@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('juniorhr', 'juniorhr@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('projectowner', 'projectowner@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('programmanager', 'programmanager@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('deliverymanager', 'deliverymanager@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('projectmanager', 'projectmanager@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('teamlead', 'teamlead@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('employee', 'employee@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1),
('intern', 'intern@erm.local', '$2a$10$YlYBXJIZ2GeCWVn1MaQbIOF7Pj1mC04lhlyiR.Jz7J4RSYeLW1PLq', 1);

INSERT IGNORE INTO ERM_USER_ROLES (USER_ID, ROLE_ID)
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Super Admin'
WHERE U.USERNAME = 'superadmin'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Admin'
WHERE U.USERNAME = 'admin'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'CEO'
WHERE U.USERNAME = 'ceo'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'CFO'
WHERE U.USERNAME = 'cfo'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'CTO'
WHERE U.USERNAME = 'cto'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'CHRO'
WHERE U.USERNAME = 'chro'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'HR Head'
WHERE U.USERNAME = 'hrhead'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Senior HR'
WHERE U.USERNAME = 'seniorhr'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Junior HR'
WHERE U.USERNAME = 'juniorhr'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Project Owner'
WHERE U.USERNAME = 'projectowner'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Program Manager'
WHERE U.USERNAME = 'programmanager'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Delivery Manager'
WHERE U.USERNAME = 'deliverymanager'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Project Manager'
WHERE U.USERNAME = 'projectmanager'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Team Lead'
WHERE U.USERNAME = 'teamlead'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Employee'
WHERE U.USERNAME = 'employee'
UNION ALL
SELECT U.ID, R.ID
FROM ERM_USERS U
JOIN ERM_ROLES R ON R.ROLE_NAME = 'Intern'
WHERE U.USERNAME = 'intern';