ALTER TABLE ERM_USERS ADD COLUMN JUNIOR_HR_USER_ID BIGINT NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS ADD COLUMN JUNIOR_HR_USER_ID BIGINT NULL;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD COLUMN CURRENT_JUNIOR_HR_USER_ID BIGINT NULL,
    ADD COLUMN CURRENT_JUNIOR_HR_NAME VARCHAR(150) NULL,
    ADD COLUMN REQUESTED_JUNIOR_HR_USER_ID BIGINT NULL,
    ADD COLUMN REQUESTED_JUNIOR_HR_NAME VARCHAR(150) NULL;

-- Preserve continuity for existing records by assigning them to the first active Junior HR.
UPDATE ERM_USERS u
SET JUNIOR_HR_USER_ID = (
    SELECT MIN(jr.ID)
    FROM ERM_USERS jr
    JOIN ERM_USER_ROLES ur ON ur.USER_ID = jr.ID
    JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
    WHERE LOWER(r.ROLE_NAME) = 'junior hr'
      AND jr.IS_ACTIVE = 1
      AND LOWER(jr.EMPLOYMENT_STATUS) = 'active'
);

UPDATE ERM_ONBOARDING_REQUESTS o
SET JUNIOR_HR_USER_ID = (
    SELECT MIN(jr.ID)
    FROM ERM_USERS jr
    JOIN ERM_USER_ROLES ur ON ur.USER_ID = jr.ID
    JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
    WHERE LOWER(r.ROLE_NAME) = 'junior hr'
      AND jr.IS_ACTIVE = 1
      AND LOWER(jr.EMPLOYMENT_STATUS) = 'active'
);

UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS p
JOIN ERM_USERS u ON u.ID = p.EMPLOYEE_USER_ID
SET p.CURRENT_JUNIOR_HR_USER_ID = u.JUNIOR_HR_USER_ID,
    p.REQUESTED_JUNIOR_HR_USER_ID = u.JUNIOR_HR_USER_ID;

UPDATE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS p
JOIN ERM_USERS jr ON jr.ID = p.CURRENT_JUNIOR_HR_USER_ID
SET p.CURRENT_JUNIOR_HR_NAME = COALESCE(NULLIF(TRIM(jr.FULL_NAME), ''), jr.USERNAME),
    p.REQUESTED_JUNIOR_HR_NAME = COALESCE(NULLIF(TRIM(jr.FULL_NAME), ''), jr.USERNAME);

ALTER TABLE ERM_USERS MODIFY COLUMN JUNIOR_HR_USER_ID BIGINT NOT NULL;
ALTER TABLE ERM_ONBOARDING_REQUESTS MODIFY COLUMN JUNIOR_HR_USER_ID BIGINT NOT NULL;
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    MODIFY COLUMN REQUESTED_JUNIOR_HR_USER_ID BIGINT NOT NULL,
    MODIFY COLUMN REQUESTED_JUNIOR_HR_NAME VARCHAR(150) NOT NULL;

CREATE INDEX IDX_ERM_USERS_JUNIOR_HR_USER_ID ON ERM_USERS (JUNIOR_HR_USER_ID);
CREATE INDEX IDX_ERM_ONBOARDING_JUNIOR_HR_USER_ID ON ERM_ONBOARDING_REQUESTS (JUNIOR_HR_USER_ID);
ALTER TABLE ERM_USERS
    ADD CONSTRAINT FK_ERM_USERS_JUNIOR_HR FOREIGN KEY (JUNIOR_HR_USER_ID) REFERENCES ERM_USERS (ID);
ALTER TABLE ERM_ONBOARDING_REQUESTS
    ADD CONSTRAINT FK_ERM_ONBOARDING_JUNIOR_HR FOREIGN KEY (JUNIOR_HR_USER_ID) REFERENCES ERM_USERS (ID);
ALTER TABLE ERM_EMPLOYEE_PROFILE_UPDATE_REQUESTS
    ADD CONSTRAINT FK_ERM_EMP_PROFILE_REQ_JUNIOR_HR FOREIGN KEY (REQUESTED_JUNIOR_HR_USER_ID) REFERENCES ERM_USERS (ID);
