-- This migration is intentionally restart-safe: MySQL may retain successful DDL
-- statements after a later statement fails, and Flyway retries after repair.
SET @erm_add_associated_hr_user_id = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_REQUESTS ADD COLUMN ASSOCIATED_HR_USER_ID BIGINT NULL',
        'SELECT 1')
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_USER_ID'
);
PREPARE erm_v54_stmt FROM @erm_add_associated_hr_user_id;
EXECUTE erm_v54_stmt;
DEALLOCATE PREPARE erm_v54_stmt;

SET @erm_add_associated_hr_name = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_REQUESTS ADD COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NULL',
        'SELECT 1')
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_NAME'
);
PREPARE erm_v54_stmt FROM @erm_add_associated_hr_name;
EXECUTE erm_v54_stmt;
DEALLOCATE PREPARE erm_v54_stmt;

SET @erm_add_associated_hr_role_name = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_REQUESTS ADD COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NULL',
        'SELECT 1')
    FROM information_schema.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_ROLE_NAME'
);
PREPARE erm_v54_stmt FROM @erm_add_associated_hr_role_name;
EXECUTE erm_v54_stmt;
DEALLOCATE PREPARE erm_v54_stmt;

-- Backfill projects that do not already have an HR contact; retain existing selections.
UPDATE ERM_PROJECT_REQUESTS p
SET p.ASSOCIATED_HR_USER_ID = COALESCE(
    p.ASSOCIATED_HR_USER_ID,
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'junior hr'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active'),
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'senior hr'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active'),
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'hr head'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active')
);

UPDATE ERM_PROJECT_REQUESTS p
JOIN ERM_USERS u ON u.ID = p.ASSOCIATED_HR_USER_ID
SET p.ASSOCIATED_HR_NAME = COALESCE(NULLIF(TRIM(u.FULL_NAME), ''), u.USERNAME),
    p.ASSOCIATED_HR_ROLE_NAME = CASE
        WHEN EXISTS (SELECT 1 FROM ERM_USER_ROLES ur JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
                     WHERE ur.USER_ID = u.ID AND LOWER(r.ROLE_NAME) = 'junior hr') THEN 'Junior HR'
        WHEN EXISTS (SELECT 1 FROM ERM_USER_ROLES ur JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
                     WHERE ur.USER_ID = u.ID AND LOWER(r.ROLE_NAME) = 'senior hr') THEN 'Senior HR'
        ELSE 'HR Head'
    END;

ALTER TABLE ERM_PROJECT_REQUESTS
    MODIFY COLUMN ASSOCIATED_HR_USER_ID BIGINT NOT NULL,
    MODIFY COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NOT NULL,
    MODIFY COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NOT NULL;

SET @erm_add_associated_hr_fk = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_REQUESTS ADD CONSTRAINT FK_ERM_PROJECT_REQUESTS_ASSOCIATED_HR FOREIGN KEY (ASSOCIATED_HR_USER_ID) REFERENCES ERM_USERS (ID)',
        'SELECT 1')
    FROM information_schema.KEY_COLUMN_USAGE
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_USER_ID'
      AND REFERENCED_TABLE_NAME = 'ERM_USERS'
);
PREPARE erm_v54_stmt FROM @erm_add_associated_hr_fk;
EXECUTE erm_v54_stmt;
DEALLOCATE PREPARE erm_v54_stmt;

SET @erm_add_associated_hr_index = (
    SELECT IF(COUNT(*) = 0,
        'CREATE INDEX IDX_ERM_PROJECT_REQUESTS_ASSOCIATED_HR ON ERM_PROJECT_REQUESTS (ASSOCIATED_HR_USER_ID)',
        'SELECT 1')
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_USER_ID'
);
PREPARE erm_v54_stmt FROM @erm_add_associated_hr_index;
EXECUTE erm_v54_stmt;
DEALLOCATE PREPARE erm_v54_stmt;
