ALTER TABLE ERM_PROJECT_REQUESTS
    ADD COLUMN ASSOCIATED_HR_USER_ID BIGINT NULL,
    ADD COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NULL,
    ADD COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NULL;

-- Backfill existing projects to an active HR contact.
UPDATE ERM_PROJECT_REQUESTS p
SET p.ASSOCIATED_HR_USER_ID = COALESCE(
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'junior hr'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active'),
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'senior hr'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active'),
    (SELECT MIN(u.ID) FROM ERM_USERS u JOIN ERM_USER_ROLES ur ON ur.USER_ID = u.ID
     JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID WHERE LOWER(r.ROLE_NAME) = 'hr head'
       AND u.IS_ACTIVE = 1 AND LOWER(u.EMPLOYMENT_STATUS) = 'active')
);

UPDATE ERM_PROJECT_REQUESTS p
JOIN ERM_USERS u ON u.ID = p.ASSOCIATED_HR_USER_ID
SET p.ASSOCIATED_HR_NAME = COALESCE(NULLIF(TRIM(u.FULL_NAME), ''), u.USERNAME),
    p.ASSOCIATED_HR_ROLE_NAME = CASE
        WHEN EXISTS (SELECT 1 FROM ERM_USER_ROLES ur JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
                     WHERE ur.USER_ID = u.ID AND LOWER(r.ROLE_NAME) = 'junior hr') THEN 'Junior HR'
        WHEN EXISTS (SELECT 1 FROM ERM_USER_ROLES ur JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
                     WHERE ur.USER_ID = u.ID AND LOWER(r.ROLE_NAME) = 'senior hr') THEN 'Senior HR'
        ELSE 'HR Head'
    END;

ALTER TABLE ERM_PROJECT_REQUESTS
    MODIFY COLUMN ASSOCIATED_HR_USER_ID BIGINT NOT NULL,
    MODIFY COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NOT NULL,
    MODIFY COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NOT NULL,
    ADD CONSTRAINT FK_ERM_PROJECT_REQUESTS_ASSOCIATED_HR
        FOREIGN KEY (ASSOCIATED_HR_USER_ID) REFERENCES ERM_USERS (ID);

CREATE INDEX IDX_ERM_PROJECT_REQUESTS_ASSOCIATED_HR
    ON ERM_PROJECT_REQUESTS (ASSOCIATED_HR_USER_ID);
