ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS
    ADD COLUMN ASSOCIATED_HR_USER_ID BIGINT NULL,
    ADD COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NULL,
    ADD COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NULL,
    ADD CONSTRAINT FK_ERM_PROJECT_CHANGE_REQUESTS_ASSOCIATED_HR
        FOREIGN KEY (ASSOCIATED_HR_USER_ID) REFERENCES ERM_USERS (ID);
