-- Add columns independently from the foreign key: MySQL validates a foreign
-- key during ALTER parsing, before columns in that same ALTER are available.
SET @erm_v57_hrbp_user_id = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD COLUMN ASSOCIATED_HR_USER_ID BIGINT NULL',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_CHANGE_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_USER_ID'
);
PREPARE erm_v57_stmt FROM @erm_v57_hrbp_user_id;
EXECUTE erm_v57_stmt;
DEALLOCATE PREPARE erm_v57_stmt;

SET @erm_v57_hrbp_name = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD COLUMN ASSOCIATED_HR_NAME VARCHAR(150) NULL',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_CHANGE_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_NAME'
);
PREPARE erm_v57_stmt FROM @erm_v57_hrbp_name;
EXECUTE erm_v57_stmt;
DEALLOCATE PREPARE erm_v57_stmt;

SET @erm_v57_hrbp_role = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD COLUMN ASSOCIATED_HR_ROLE_NAME VARCHAR(100) NULL',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_CHANGE_REQUESTS'
      AND COLUMN_NAME = 'ASSOCIATED_HR_ROLE_NAME'
);
PREPARE erm_v57_stmt FROM @erm_v57_hrbp_role;
EXECUTE erm_v57_stmt;
DEALLOCATE PREPARE erm_v57_stmt;

SET @erm_v57_hrbp_fk = (
    SELECT IF(COUNT(*) = 0,
        'ALTER TABLE ERM_PROJECT_CHANGE_REQUESTS ADD CONSTRAINT FK_ERM_PROJECT_CHANGE_REQUESTS_ASSOCIATED_HR FOREIGN KEY (ASSOCIATED_HR_USER_ID) REFERENCES ERM_USERS (ID)',
        'SELECT 1')
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_SCHEMA = DATABASE()
      AND TABLE_NAME = 'ERM_PROJECT_CHANGE_REQUESTS'
      AND CONSTRAINT_NAME = 'FK_ERM_PROJECT_CHANGE_REQUESTS_ASSOCIATED_HR'
      AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
PREPARE erm_v57_stmt FROM @erm_v57_hrbp_fk;
EXECUTE erm_v57_stmt;
DEALLOCATE PREPARE erm_v57_stmt;
