CREATE TABLE IF NOT EXISTS ERM_PROJECT_CHANGE_HRBP (
    PROJECT_CHANGE_REQUEST_ID BIGINT NOT NULL PRIMARY KEY,
    ASSOCIATED_HR_USER_ID BIGINT NOT NULL,
    INDEX IDX_PROJECT_CHANGE_HRBP_USER (ASSOCIATED_HR_USER_ID)
);
