ALTER TABLE ERM_ONBOARDING_REQUESTS
    ADD COLUMN WORKFLOW_STAGE VARCHAR(40) NOT NULL DEFAULT 'HR_SUBMITTED',
    ADD COLUMN CREATED_BY_USERNAME VARCHAR(100) NOT NULL DEFAULT 'legacy',
    ADD COLUMN HR_COMMENT VARCHAR(500) NULL,
    ADD COLUMN HEAD_HR_COMMENT VARCHAR(500) NULL,
    ADD COLUMN CHRO_COMMENT VARCHAR(500) NULL,
    ADD COLUMN SUPER_ADMIN_COMMENT VARCHAR(500) NULL,
    ADD COLUMN HR_ACTION_BY VARCHAR(100) NULL,
    ADD COLUMN HEAD_HR_ACTION_BY VARCHAR(100) NULL,
    ADD COLUMN CHRO_ACTION_BY VARCHAR(100) NULL,
    ADD COLUMN SUPER_ADMIN_ACTION_BY VARCHAR(100) NULL,
    ADD COLUMN HR_ACTION_AT TIMESTAMP NULL,
    ADD COLUMN HEAD_HR_ACTION_AT TIMESTAMP NULL,
    ADD COLUMN CHRO_ACTION_AT TIMESTAMP NULL,
    ADD COLUMN SUPER_ADMIN_ACTION_AT TIMESTAMP NULL;

UPDATE ERM_ONBOARDING_REQUESTS
SET WORKFLOW_STAGE = CASE
    WHEN INTERVIEW_STAGE = 'COMPLETED' THEN 'SUPER_ADMIN_APPROVED'
    WHEN INTERVIEW_STAGE = 'REJECTED' THEN 'REJECTED'
    ELSE 'HR_SUBMITTED'
END,
    CREATED_BY_USERNAME = 'legacy',
    HR_ACTION_BY = 'legacy',
    HR_ACTION_AT = CREATED_AT
WHERE CREATED_BY_USERNAME = 'legacy';

INSERT INTO ERM_NAV_MENUS (MENU_CODE, MENU_TITLE, MENU_PATH, MENU_ICON, SORT_ORDER, IS_ACTIVE)
SELECT 'onboarding', 'On-Boarding', '/onboarding', 'user-round-plus', 3, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_NAV_MENUS WHERE MENU_CODE = 'onboarding');

UPDATE ERM_NAV_MENUS
SET SORT_ORDER = SORT_ORDER + 1
WHERE MENU_CODE IN ('projects', 'attendance', 'leaves', 'settings');

INSERT IGNORE INTO ERM_ROLE_NAV_MENUS (ROLE_ID, MENU_ID)
SELECT r.ID, m.ID
FROM ERM_ROLES r
JOIN ERM_NAV_MENUS m ON m.MENU_CODE = 'onboarding'
WHERE r.ROLE_NAME IN ('Super Admin', 'CHRO', 'HR Head', 'Senior HR', 'Junior HR');
