CREATE TABLE ERM_DESIGNATION_HIERARCHY
(
    ID                    BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESIGNATION_ROLE_NAME VARCHAR(100) NOT NULL,
    REPORTS_TO_ROLE_NAME  VARCHAR(100) NOT NULL,
    SORT_ORDER            INT          NOT NULL DEFAULT 0,
    IS_ACTIVE             BIT          NOT NULL DEFAULT 1,
    CREATED_AT            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_ERM_DESIGNATION_ROLE_NAME (DESIGNATION_ROLE_NAME)
);

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Intern', 'Employee', 10, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Intern');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Employee', 'Team Lead', 20, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Employee');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Team Lead', 'Project Manager', 30, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Team Lead');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Project Manager', 'Delivery Manager', 40, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Project Manager');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Delivery Manager', 'Program Manager', 50, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Delivery Manager');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Program Manager', 'Project Owner', 60, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Program Manager');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Project Owner', 'CTO', 70, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Project Owner');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Junior HR', 'Senior HR', 80, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Junior HR');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'Senior HR', 'HR Head', 90, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'Senior HR');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'HR Head', 'CHRO', 100, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'HR Head');

INSERT INTO ERM_DESIGNATION_HIERARCHY (DESIGNATION_ROLE_NAME, REPORTS_TO_ROLE_NAME, SORT_ORDER, IS_ACTIVE)
SELECT 'CHRO', 'Super Admin', 110, 1
WHERE NOT EXISTS (SELECT 1 FROM ERM_DESIGNATION_HIERARCHY WHERE DESIGNATION_ROLE_NAME = 'CHRO');

ALTER TABLE ERM_ONBOARDING_REQUESTS
    ADD COLUMN DESIGNATION_ROLE_NAME VARCHAR(100) NULL,
    ADD COLUMN REPORTING_MANAGER_USER_ID BIGINT NULL,
    ADD COLUMN REPORTING_MANAGER_USERNAME VARCHAR(100) NULL,
    ADD COLUMN REPORTING_MANAGER_FULL_NAME VARCHAR(150) NULL,
    ADD COLUMN REPORTING_MANAGER_ROLE_NAME VARCHAR(100) NULL;

UPDATE ERM_ONBOARDING_REQUESTS
SET DESIGNATION_ROLE_NAME = 'Employee'
WHERE DESIGNATION_ROLE_NAME IS NULL;

CREATE INDEX IDX_ERM_ONBOARDING_DESIGNATION ON ERM_ONBOARDING_REQUESTS (DESIGNATION_ROLE_NAME);
CREATE INDEX IDX_ERM_ONBOARDING_REPORTING_MANAGER_USER_ID ON ERM_ONBOARDING_REQUESTS (REPORTING_MANAGER_USER_ID);
