ALTER TABLE ERM_USERS
    ADD COLUMN REPORTING_MANAGER_USER_ID BIGINT NULL,
    ADD COLUMN REPORTING_MANAGER_ROLE_NAME VARCHAR(100) NULL;

UPDATE ERM_USERS
SET REPORTING_MANAGER_ROLE_NAME = NULL,
    REPORTING_MANAGER_USER_ID = NULL;

UPDATE ERM_USERS u
SET REPORTING_MANAGER_ROLE_NAME = (
    SELECT MIN(h.REPORTS_TO_ROLE_NAME)
    FROM ERM_USER_ROLES ur
    JOIN ERM_ROLES r ON r.ID = ur.ROLE_ID
    JOIN ERM_DESIGNATION_HIERARCHY h ON h.DESIGNATION_ROLE_NAME = r.ROLE_NAME
    WHERE ur.USER_ID = u.ID
      AND h.IS_ACTIVE = 1
);

UPDATE ERM_USERS u
SET REPORTING_MANAGER_USER_ID = (
    SELECT MIN(m.ID)
    FROM ERM_ROLES mr
    JOIN ERM_USER_ROLES mur ON mur.ROLE_ID = mr.ID
    JOIN ERM_USERS m ON m.ID = mur.USER_ID
    WHERE mr.ROLE_NAME = u.REPORTING_MANAGER_ROLE_NAME
      AND m.IS_ACTIVE = 1
      AND LOWER(m.EMPLOYMENT_STATUS) = 'active'
      AND m.ID <> u.ID
)
WHERE u.REPORTING_MANAGER_ROLE_NAME IS NOT NULL;

CREATE INDEX IDX_ERM_USERS_REPORTING_MANAGER_USER_ID ON ERM_USERS (REPORTING_MANAGER_USER_ID);
CREATE INDEX IDX_ERM_USERS_REPORTING_MANAGER_ROLE_NAME ON ERM_USERS (REPORTING_MANAGER_ROLE_NAME);
